In [226]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

In [227]:
df=pd.read_csv('income.csv')
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income_>50K
0,67,Private,366425,Doctorate,16,Divorced,Exec-managerial,Not-in-family,White,Male,99999,0,60,United-States,1
1,17,Private,244602,12th,8,Never-married,Other-service,Own-child,White,Male,0,0,15,United-States,0
2,31,Private,174201,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,1
3,58,State-gov,110199,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,0
4,25,State-gov,149248,Some-college,10,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,United-States,0

In [228]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income_>50K'],
      dtype='object')

In [229]:
df.sample(20)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income_>50K
22924,36,Private,129591,HS-grad,9,Never-married,Other-service,Not-in-family,White,Male,0,0,40,United-States,0
7255,50,Private,33931,HS-grad,9,Divorced,Craft-repair,Not-in-family,White,Male,0,0,40,United-States,0
35931,28,Private,175262,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,0
28305,17,Private,19752,11th,7,Never-married,Other-service,Own-child,Black,Female,0,0,25,United-States,0
15719,32,Local-gov,190889,Masters,14,Never-married,Prof-specialty,Not-in-family,Other,Female,0,0,40,NaN,0
33138,62,Private,244933,Masters,14,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,45,United-States,0
25489,47,Private,145868,11th,7,Divorced,Other-service,Unmarried,Black,Female,0,0,40,United-States,0
180,53,Private,590941,Doctorate,16,Never-married,Prof-specialty,Unmarried,White,Female,0,1408,40,United-States,0
32385,18,NaN,151866,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,0
41019,35,Private,231180,HS-grad,9,Divorced,Transport-moving,Not-in-family,White,Male,0,0,60,United-States,0
16142,30,Private,233433,HS-grad,9,Never-married,Sales,Own-child,White,Female,0,0,45,United-States,0
29673,21,Private,329174,HS-grad,9,Never-married,Tech-support,Not-in-family,White,Male,4865,0,40,United-States,0
22354,22,Private,171538,HS-grad,9,Divorced,Other-service,Own-child,White,Female,0,0,35,United-States,0
14296,29,Private,40295,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,0
417,22,Private,315476,11th,7,Never-married,Craft-repair,Unmarried,White,Male,0,0,40,United-States,0
11092,28,Private,22422,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,40,United-States,0
2040,30,Never-worked,176673,HS-grad,9,Married-civ-spouse,NaN,Wife,Black,Female,0,0,40,United-States,0
41013,38,Private,33394,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,75,United-States,1
30428,25,Private,182866,HS-grad,9,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,0
14967,32,Self-emp-not-inc,198613,Bachelors,13,Never-married,Sales,Not-in-family,White,Male,0,0,45,NaN,1

In [230]:
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income_>50K
0,67,Private,366425,Doctorate,16,Divorced,Exec-managerial,Not-in-family,White,Male,99999,0,60,United-States,1
1,17,Private,244602,12th,8,Never-married,Other-service,Own-child,White,Male,0,0,15,United-States,0
2,31,Private,174201,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,1
3,58,State-gov,110199,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,0
4,25,State-gov,149248,Some-college,10,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,United-States,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43952,52,Private,68982,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,1
43953,19,Private,116562,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,40,United-States,0
43954,30,Private,197947,Some-college,10,Divorced,Sales,Not-in-family,White,Male,0,0,58,United-States,0
43955,46,Private,97883,Bachelors,13,Never-married,Sales,Not-in-family,White,Female,0,0,35,United-States,0
43956,30,Private,375827,HS-grad,9,Never-married,Handlers-cleaners,Other-relative,White,Male,0,0,40,United-States,0

In [231]:
df['occupation'].unique()

array(['Exec-managerial', 'Other-service', 'Transport-moving',
       'Adm-clerical', 'Machine-op-inspct', 'Sales', 'Handlers-cleaners',
       'Farming-fishing', 'Protective-serv', 'Prof-specialty',
       'Craft-repair', nan, 'Tech-support', 'Priv-house-serv',
       'Armed-Forces'], dtype=object)

In [232]:
df['education'].unique()

array(['Doctorate', '12th', 'Bachelors', '7th-8th', 'Some-college',
       'HS-grad', '9th', '10th', '11th', 'Masters', 'Preschool',
       '5th-6th', 'Prof-school', 'Assoc-voc', '1st-4th', 'Assoc-acdm'],
      dtype=object)

In [233]:
df['marital-status'].unique()

array(['Divorced', 'Never-married', 'Married-civ-spouse', 'Widowed',
       'Separated', 'Married-spouse-absent', 'Married-AF-spouse'],
      dtype=object)

In [234]:
missing_values = df.isnull().sum()

print(missing_values)

age                   0
workclass          2498
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2506
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      763
income_>50K           0
dtype: int64

In [235]:
df['workclass'].value_counts()

workclass
Private             30587
Self-emp-not-inc     3464
Local-gov            2822
State-gov            1756
Self-emp-inc         1518
Federal-gov          1284
Without-pay            20
Never-worked            8
Name: count, dtype: int64

In [236]:
df['native-country'].value_counts()

native-country
United-States                 39429
Mexico                          880
Philippines                     273
Germany                         188
Puerto-Rico                     167
Canada                          158
El-Salvador                     145
India                           134
Cuba                            124
China                           113
England                         109
South                           105
Jamaica                          97
Dominican-Republic               97
Italy                            94
Japan                            83
Guatemala                        79
Vietnam                          77
Columbia                         75
Poland                           72
Haiti                            71
Portugal                         59
Taiwan                           58
Iran                             52
Nicaragua                        46
Greece                           44
Ecuador                          42
Peru                             40
Ireland                          32
France                           32
Hong                             29
Thailand                         29
Cambodia                         24
Trinadad&Tobago                  22
Honduras                         20
Yugoslavia                       19
Scotland                         19
Outlying-US(Guam-USVI-etc)       19
Laos                             19
Hungary                          18
Holand-Netherlands                1
Name: count, dtype: int64

In [237]:
missing_matrix = df.isnull().astype(int)
missing_corr = missing_matrix.corr()

print(missing_corr)

                 age  workclass  fnlwgt  education  educational-num  \
age              NaN        NaN     NaN        NaN              NaN
workclass        NaN   1.000000     NaN        NaN              NaN
fnlwgt           NaN        NaN     NaN        NaN              NaN
education        NaN        NaN     NaN        NaN              NaN
educational-num  NaN        NaN     NaN        NaN              NaN
marital-status   NaN        NaN     NaN        NaN              NaN
occupation       NaN   0.998306     NaN        NaN              NaN
relationship     NaN        NaN     NaN        NaN              NaN
race             NaN        NaN     NaN        NaN              NaN
gender           NaN        NaN     NaN        NaN              NaN
capital-gain     NaN        NaN     NaN        NaN              NaN
capital-loss     NaN        NaN     NaN        NaN              NaN
hours-per-week   NaN        NaN     NaN        NaN              NaN
native-country   NaN  -0.003280     NaN        NaN              NaN
income_>50K      NaN        NaN     NaN        NaN              NaN

                 marital-status  occupation  relationship  race  gender  \
age                         NaN         NaN           NaN   NaN     NaN
workclass                   NaN    0.998306           NaN   NaN     NaN
fnlwgt                      NaN         NaN           NaN   NaN     NaN
education                   NaN         NaN           NaN   NaN     NaN
educational-num             NaN         NaN           NaN   NaN     NaN
marital-status              NaN         NaN           NaN   NaN     NaN
occupation                  NaN    1.000000           NaN   NaN     NaN
relationship                NaN         NaN           NaN   NaN     NaN
race                        NaN         NaN           NaN   NaN     NaN
gender                      NaN         NaN           NaN   NaN     NaN
capital-gain                NaN         NaN           NaN   NaN     NaN
capital-loss                NaN         NaN           NaN   NaN     NaN
hours-per-week              NaN         NaN           NaN   NaN     NaN
native-country              NaN   -0.003380           NaN   NaN     NaN
income_>50K                 NaN         NaN           NaN   NaN     NaN

                 capital-gain  capital-loss  hours-per-week  native-country  \
age                       NaN           NaN             NaN             NaN
workclass                 NaN           NaN             NaN        -0.00328
fnlwgt                    NaN           NaN             NaN             NaN
education                 NaN           NaN             NaN             NaN
educational-num           NaN           NaN             NaN             NaN
marital-status            NaN           NaN             NaN             NaN
occupation                NaN           NaN             NaN        -0.00338
relationship              NaN           NaN             NaN             NaN
race                      NaN           NaN             NaN             NaN
gender                    NaN           NaN             NaN             NaN
capital-gain              NaN           NaN             NaN             NaN
capital-loss              NaN           NaN             NaN             NaN
hours-per-week            NaN           NaN             NaN             NaN
native-country            NaN           NaN             NaN         1.00000
income_>50K               NaN           NaN             NaN             NaN

                 income_>50K
age                      NaN
workclass                NaN
fnlwgt                   NaN
education                NaN
educational-num          NaN
marital-status           NaN
occupation               NaN
relationship             NaN
race                     NaN
gender                   NaN
capital-gain             NaN
capital-loss             NaN
hours-per-week           NaN
native-country           NaN
income_>50K              NaN

In [238]:
df_train = df[df['workclass'].notna() & df['occupation'].notna()]
df_missing_workclass = df[df['workclass'].isna()]

features = ['education', 'educational-num', 'marital-status',
            'relationship', 'race', 'gender', 'hours-per-week']
df_encoded = df_train.copy()
label_encoders={}
for i in features +['workclass']+['occupation']:
    if df_encoded[i].dtype == 'object':
        le = LabelEncoder()
        df_encoded[i] = le.fit_transform(df_encoded[i])
        label_encoders[i] = le

In [239]:
X_train = df_encoded[features]
y_train = df_encoded[['workclass', 'occupation']]
clf_workclass = RandomForestClassifier()
clf_workclass.fit(X_train, y_train)

RandomForestClassifier()

In [240]:
df_missing = df_missing_workclass.copy()
for col in features:
    if df_missing[col].dtype == 'object':
        df_missing[col] = label_encoders[col].transform(df_missing[col])
X_missing = df_missing[features]
y_pred = clf_workclass.predict(X_missing)
df_missing['workclass'] = label_encoders['workclass'].inverse_transform(y_pred[:,0])
df_missing['occupation'] = label_encoders['occupation'].inverse_transform(y_pred[:,1])

In [241]:
df.loc[df['workclass'].isna(), 'workclass'] = df_missing['workclass']
df.loc[df['occupation'].isna(), 'occupation'] = df_missing['occupation']

In [242]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income_>50K
0,67,Private,366425,Doctorate,16,Divorced,Exec-managerial,Not-in-family,White,Male,99999,0,60,United-States,1
1,17,Private,244602,12th,8,Never-married,Other-service,Own-child,White,Male,0,0,15,United-States,0
2,31,Private,174201,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,1
3,58,State-gov,110199,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,0
4,25,State-gov,149248,Some-college,10,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,United-States,0

In [243]:
df = df.dropna(subset=['native-country'])

missing_values = df.isnull().sum()

print(missing_values)

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         8
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income_>50K        0
dtype: int64